LanguageNames=(Japanese=0x411:MSG00411)
MessageId=1
Severity=Error
Facility=Application
SymbolicName=EVENTLOG_MSG_OTHER_ERROR
Language=Japanese
その他のエラーが発生しました。
.
MessageId=2
Severity=Warning
Facility=Application
SymbolicName=EVENTLOG_MSG_OTHER_WARNING
Language=Japanese
その他の警告が発生しました。
.
MessageId=3
Severity=Informational
Facility=Application
SymbolicName=EVENTLOG_MSG_OTHER_INFORMATION
Language=Japanese
その他の情報が発生しました。
.
